# Generated by Django 3.2.12 on 2021-06-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("whatChapter", "0002_alter_anime_anime_name")]

    operations = [
        migrations.AlterModelManagers(name="user", managers=[]),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
