# Generated by Django 3.2.12 on 2021-06-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatChapter', '0003_auto_20220408_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='studio',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
