# Generated by Django 3.2.12 on  2021-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatChapter', '0004_auto_20220409_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studio',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
