# Generated by Django 3.2.12 on 2021-06-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("whatChapter", "0005_auto_20220409_1552")]

    operations = [
        migrations.AddField(
            model_name="anime", name="chapter", field=models.IntegerField(null=True)
        )
    ]
